/**
 * Static game data used by both the agent tool-executor and the
 * /api/agent/tools/game-data endpoint.
 *
 * Single source of truth — no duplication in Kotlin.
 */

// ── Formations ──────────────────────────────────────────────────────────────

export interface FormationData {
  id: string;
  name: string;
  positions: string[];
  style: string;
  description: string;
}

export const FORMATIONS: FormationData[] = [
  { id: '433', name: '4-3-3', positions: ['GK','LB','CB','CB','RB','CM','CM','CM','LW','ST','RW'], style: 'attacking', description: 'Wide attacking formation with wingers stretching the defense.' },
  { id: '4231', name: '4-2-3-1', positions: ['GK','LB','CB','CB','RB','CDM','CDM','LW','CAM','RW','ST'], style: 'balanced', description: 'Versatile formation with double pivot and attacking midfield.' },
  { id: '442', name: '4-4-2', positions: ['GK','LB','CB','CB','RB','LM','CM','CM','RM','ST','ST'], style: 'balanced', description: 'Classic balanced formation with dual striker partnership.' },
  { id: '41212-2', name: '4-1-2-1-2 (2)', positions: ['GK','LB','CB','CB','RB','CDM','CM','CM','CAM','ST','ST'], style: 'attacking', description: 'Narrow diamond with two strikers. Great for through-ball play.' },
  { id: '4321', name: '4-3-2-1', positions: ['GK','LB','CB','CB','RB','CM','CM','CM','LF','ST','RF'], style: 'attacking', description: 'Narrow attacking formation with inside forwards.' },
  { id: '4222', name: '4-2-2-2', positions: ['GK','LB','CB','CB','RB','CDM','CDM','CAM','CAM','ST','ST'], style: 'attacking', description: 'Double pivot with dual CAMs and strikers.' },
  { id: '352', name: '3-5-2', positions: ['GK','CB','CB','CB','CDM','CDM','LM','RM','CAM','ST','ST'], style: 'attacking', description: 'Wing play with 3 at the back. LM/RM must track back.' },
  { id: '5212', name: '5-2-1-2', positions: ['GK','LWB','CB','CB','CB','RWB','CM','CM','CAM','ST','ST'], style: 'defensive', description: 'Five at the back with wing-backs and dual strikers.' },
  { id: '4141', name: '4-1-4-1', positions: ['GK','LB','CB','CB','RB','CDM','LM','CM','CM','RM','ST'], style: 'balanced', description: 'Wide midfield with single holding midfielder.' },
  { id: '4411', name: '4-4-1-1', positions: ['GK','LB','CB','CB','RB','LM','CM','CM','RM','CAM','ST'], style: 'balanced', description: 'Classic formation with CAM supporting the striker.' },
  { id: '4132', name: '4-1-3-2', positions: ['GK','LB','CB','CB','RB','CDM','LM','CAM','RM','ST','ST'], style: 'attacking', description: 'Wide midfield with CDM and two strikers.' },
  { id: '343', name: '3-4-3', positions: ['GK','CB','CB','CB','LM','CM','CM','RM','LW','ST','RW'], style: 'attacking', description: 'Ultra-attacking with 3 forwards and 3 at the back.' },
  { id: '4312', name: '4-3-1-2', positions: ['GK','LB','CB','CB','RB','CM','CM','CM','CAM','ST','ST'], style: 'attacking', description: 'Midfield diamond with CAM behind two strikers.' },
  { id: '433-4', name: '4-3-3 (4)', positions: ['GK','LB','CB','CB','RB','CM','CM','CAM','LW','ST','RW'], style: 'attacking', description: '4-3-3 variant with a dedicated CAM.' },
  { id: '4231-2', name: '4-2-3-1 (2)', positions: ['GK','LB','CB','CB','RB','CDM','CDM','LM','CAM','RM','ST'], style: 'balanced', description: '4-2-3-1 with wide mids instead of wingers.' },
  { id: '541', name: '5-4-1', positions: ['GK','LWB','CB','CB','CB','RWB','LM','CM','CM','RM','ST'], style: 'defensive', description: 'Ultra-defensive 5-back with wide mids.' },
  { id: '532', name: '5-3-2', positions: ['GK','LWB','CB','CB','CB','RWB','CM','CM','CM','ST','ST'], style: 'balanced', description: 'Solid 5-back with midfield 3 and two strikers.' },
  { id: '3412', name: '3-4-1-2', positions: ['GK','CB','CB','CB','LM','CM','CM','RM','CAM','ST','ST'], style: 'attacking', description: '3-back with wide mids and CAM supporting two strikers.' },
  { id: '451', name: '4-5-1', positions: ['GK','LB','CB','CB','RB','LM','CM','CM','CM','RM','ST'], style: 'balanced', description: 'Packed midfield with lone striker.' },
  { id: '442-2', name: '4-4-2 (2)', positions: ['GK','LB','CB','CB','RB','LM','CDM','CDM','RM','ST','ST'], style: 'defensive', description: '4-4-2 with double CDM pivot.' },
];

// ── Chem Styles ─────────────────────────────────────────────────────────────

export interface ChemStyleData {
  name: string;
  category: string;
  boosts: { stat: string; amount1: number; amount2: number; amount3: number }[];
  bestPositions: string[];
  description: string;
}

export const CHEM_STYLES: ChemStyleData[] = [
  { name: 'Hunter', category: 'premium', boosts: [{ stat: 'pace', amount1: 2, amount2: 4, amount3: 6 }, { stat: 'shooting', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['ST', 'LW', 'RW'], description: 'Pace + shooting for attackers' },
  { name: 'Shadow', category: 'premium', boosts: [{ stat: 'pace', amount1: 2, amount2: 4, amount3: 6 }, { stat: 'defending', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['CB', 'LB', 'RB', 'CDM'], description: 'The defensive meta chem style' },
  { name: 'Finisher', category: 'premium', boosts: [{ stat: 'shooting', amount1: 2, amount2: 4, amount3: 6 }, { stat: 'dribbling', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['ST', 'CF'], description: 'Max finishing + dribbling at 3 chem' },
  { name: 'Catalyst', category: 'hybrid', boosts: [{ stat: 'pace', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'passing', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['LB', 'RB', 'LM', 'RM'], description: 'Fast playmaker' },
  { name: 'Anchor', category: 'triple', boosts: [{ stat: 'pace', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CB', 'CDM', 'LB', 'RB'], description: 'Well-rounded defense' },
  { name: 'Hawk', category: 'triple', boosts: [{ stat: 'pace', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['ST', 'CF'], description: 'Physical finishing' },
  { name: 'Engine', category: 'triple', boosts: [{ stat: 'pace', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CM', 'CAM', 'LM', 'RM'], description: 'All-around midfield' },
  { name: 'Sniper', category: 'basic', boosts: [{ stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['ST', 'CAM'], description: 'Agile finishers' },
  { name: 'Marksman', category: 'triple', boosts: [{ stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['ST', 'CF'], description: 'Balanced attack' },
  { name: 'Deadeye', category: 'basic', boosts: [{ stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CAM', 'CF'], description: 'Playmaker finishing' },
  { name: 'Maestro', category: 'triple', boosts: [{ stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CAM', 'CM'], description: 'Creative maestro' },
  { name: 'Artist', category: 'basic', boosts: [{ stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CM', 'CAM'], description: 'Technical passer' },
  { name: 'Architect', category: 'basic', boosts: [{ stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CM', 'CDM'], description: 'Physical passer' },
  { name: 'Powerhouse', category: 'basic', boosts: [{ stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CDM', 'CM'], description: 'Defensive midfielder' },
  { name: 'Sentinel', category: 'basic', boosts: [{ stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CB'], description: 'Pure defender' },
  { name: 'Guardian', category: 'basic', boosts: [{ stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CB', 'CDM'], description: 'Ball-playing defender' },
  { name: 'Backbone', category: 'triple', boosts: [{ stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['CDM', 'CM'], description: 'Box-to-box' },
  { name: 'Basic', category: 'basic', boosts: [{ stat: 'pace', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'shooting', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'passing', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'dribbling', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'defending', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'physical', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['ANY'], description: 'All stats +1/+2/+3 at 1/2/3 chem' },
  { name: 'Glove', category: 'gk', boosts: [{ stat: 'diving', amount1: 2, amount2: 4, amount3: 6 }, { stat: 'reflexes', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['GK'], description: 'Diving + reflexes for shot-stoppers' },
  { name: 'Shield', category: 'gk', boosts: [{ stat: 'kicking', amount1: 2, amount2: 4, amount3: 6 }, { stat: 'positioning', amount1: 2, amount2: 4, amount3: 6 }], bestPositions: ['GK'], description: 'Kicking + positioning for distribution' },
  { name: 'Wall', category: 'gk', boosts: [{ stat: 'diving', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'handling', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'kicking', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['GK'], description: 'All-round goalkeeper' },
  { name: 'Cat', category: 'gk', boosts: [{ stat: 'reflexes', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'speed', amount1: 1, amount2: 2, amount3: 3 }, { stat: 'positioning', amount1: 1, amount2: 2, amount3: 3 }], bestPositions: ['GK'], description: 'Sweeper keeper' },
];

// ── Tactical Presets (FC 26 Roles System) ──────────────────────────────────
// FC 26 replaced FC 25's depth/width sliders and player instructions with
// a Roles + Focus system. Each position has a Role and Focus modifier.

export interface TacticalPreset {
  formation: string;
  presetName: string;
  style: string;
  buildUp: string;
  defensiveApproach: string;
  roles: { position: string; role: string; focus: string }[];
  tips: { defending: string; attacking: string };
}

export const TACTICAL_PRESETS: TacticalPreset[] = [
  { formation: '4-2-3-1', presetName: 'Balanced Control', style: 'balanced', buildUp: 'Short', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'LW', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Roam' }, { position: 'RW', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Attack' }], tips: { defending: 'Use L2/LT to jockey, don\'t rush with CBs. Let CDMs track back. Switch players with right stick.', attacking: 'Build through CAM, use LW/RW cutting inside for finesse shots. L1/LB triggers runs.' } },
  { formation: '4-2-3-1', presetName: 'High Press Counter', style: 'counter', buildUp: 'Counter', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'LW', role: 'Winger - Winger', focus: 'Attack' }, { position: 'CAM', role: 'Attacking Midfielder - Shadow Striker', focus: 'Attack' }, { position: 'RW', role: 'Winger - Winger', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Press immediately after losing the ball. Use teammate contain (R1/RB) to cut passing lanes.', attacking: 'Quick transitions — send wingers on runs with through balls. Counter at pace.' } },
  { formation: '4-2-3-1', presetName: 'Defensive Lock', style: 'defensive', buildUp: 'Balanced', defensiveApproach: 'Drop Back', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Defend' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'LW', role: 'Winger - Wide Midfielder', focus: 'Defend' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Balanced' }, { position: 'RW', role: 'Winger - Wide Midfielder', focus: 'Defend' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Balanced' }], tips: { defending: 'Stay compact, let them come to you. Manual switch to CDMs to intercept passes.', attacking: 'Patient build-up, use CAM as the pivot. Wait for the right moment to release wingers.' } },
  { formation: '4-2-3-1', presetName: 'All-Out Attack', style: 'attacking', buildUp: 'Short', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CDM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CDM', role: 'Central Midfielder - Box-to-Box', focus: 'Attack' }, { position: 'LW', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'CAM', role: 'Attacking Midfielder - Shadow Striker', focus: 'Attack' }, { position: 'RW', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'High line means pace at CB is critical. Use offside trap sparingly.', attacking: 'Overload the box, use fullbacks overlapping. Short passes in the final third.' } },
  { formation: '4-3-3', presetName: 'Balanced Wings', style: 'balanced', buildUp: 'Balanced', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CM', role: 'Central Midfielder - Playmaker', focus: 'Attack' }, { position: 'LW', role: 'Winger - Winger', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'RW', role: 'Winger - Winger', focus: 'Attack' }], tips: { defending: 'Use the midfield 3 to press and recycle. One CM stays back as an anchor.', attacking: 'Width from wingers creates space. Overlap runs from fullbacks for crosses.' } },
  { formation: '4-3-3', presetName: 'Counter Wings', style: 'counter', buildUp: 'Counter', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'LW', role: 'Winger - Winger', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'RW', role: 'Winger - Winger', focus: 'Attack' }], tips: { defending: 'Compact midfield absorbs pressure. Quick press on loss to regain possession.', attacking: 'Fast transitions — long balls to pacey wingers on the break.' } },
  { formation: '4-4-2', presetName: 'Classic Flat', style: 'balanced', buildUp: 'Balanced', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'LM', role: 'Winger - Wide Midfielder', focus: 'Balanced' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'RM', role: 'Winger - Wide Midfielder', focus: 'Balanced' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Balanced' }], tips: { defending: 'Two banks of four are extremely solid. Press with strikers first, then drop back.', attacking: 'Partnership between the two strikers is key. One-two passes in the box.' } },
  { formation: '4-4-2', presetName: 'Press Machine', style: 'attacking', buildUp: 'Short', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'LM', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Attack' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'RM', role: 'Winger - Inside Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Aggressive pressing with two strikers. Fullbacks push up so pace at CB is essential.', attacking: 'Overload with fullbacks providing width. Two strikers drag defenders apart.' } },
  { formation: '4-1-2-1-2(2)', presetName: 'Narrow Diamond', style: 'balanced', buildUp: 'Short', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Attack' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Roam' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Attack' }], tips: { defending: 'Narrow shape means vulnerable on the wings. Fullbacks must get back quickly.', attacking: 'Through balls between the two strikers are lethal. CAM feeds the play. Fullbacks provide all width.' } },
  { formation: '4-1-2-1-2(2)', presetName: 'Counter Diamond', style: 'counter', buildUp: 'Counter', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RB', role: 'Full-Back - Fullback', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CAM', role: 'Attacking Midfielder - Shadow Striker', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Stay compact and force them wide. Intercept with CDM and CMs.', attacking: 'Quick transitions through the middle. Two pacey strikers run in behind.' } },
  { formation: '3-5-2', presetName: 'Wing Play', style: 'balanced', buildUp: 'Balanced', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'LM', role: 'Winger - Wide Midfielder', focus: 'Balanced' }, { position: 'RM', role: 'Winger - Wide Midfielder', focus: 'Balanced' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Attack' }], tips: { defending: 'LM/RM must track back to form a 5-man defense. 3 CBs handle the central channels.', attacking: 'Width from LM/RM is crucial. Overload centrally with CAM and two strikers.' } },
  { formation: '3-5-2', presetName: 'Attacking Overload', style: 'attacking', buildUp: 'Short', defensiveApproach: 'Press After Possession Loss', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CDM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CDM', role: 'Central Midfielder - Box-to-Box', focus: 'Attack' }, { position: 'LM', role: 'Winger - Wingback', focus: 'Attack' }, { position: 'RM', role: 'Winger - Wingback', focus: 'Attack' }, { position: 'CAM', role: 'Attacking Midfielder - Shadow Striker', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Risky — 3 CBs left exposed. Need fast CBs and a holding CDM anchor.', attacking: 'Maximum overload. Wing backs push high, CAM becomes a third striker in attack.' } },
  { formation: '5-2-1-2', presetName: 'Fortress Counter', style: 'defensive', buildUp: 'Counter', defensiveApproach: 'Drop Back', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LWB', role: 'Full-Back - Wingback', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Defend' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Defend' }, { position: 'RWB', role: 'Full-Back - Wingback', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Holding', focus: 'Defend' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Five at the back is a wall. Absorb pressure and let them waste possession.', attacking: 'Long balls to the two strikers. CAM links the play on the counter.' } },
  { formation: '5-2-1-2', presetName: 'Balanced 5-Back', style: 'balanced', buildUp: 'Balanced', defensiveApproach: 'Balanced', roles: [{ position: 'GK', role: 'Goalkeeper - Sweeper', focus: 'Balanced' }, { position: 'LWB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'CB', role: 'Centre-Back - Defender', focus: 'Balanced' }, { position: 'RWB', role: 'Full-Back - Wingback', focus: 'Attack' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CM', role: 'Central Midfielder - Box-to-Box', focus: 'Balanced' }, { position: 'CAM', role: 'Attacking Midfielder - Playmaker', focus: 'Roam' }, { position: 'ST', role: 'Striker - Target Forward', focus: 'Attack' }, { position: 'ST', role: 'Striker - Advanced Forward', focus: 'Attack' }], tips: { defending: 'Solid at the back with 3 CBs. Wing backs transition between defence and attack.', attacking: 'Wing backs provide width. Build through CAM and use striker partnership.' } },
];

// ── Skill Moves ─────────────────────────────────────────────────────────────

export interface SkillMoveData {
  name: string;
  stars: number;
  difficulty: string;
  controls: { ps: string; xbox: string };
  bestFor: string;
  when: string;
  tip: string;
}

export const SKILL_MOVES: SkillMoveData[] = [
  { name: 'Ball Roll', stars: 2, difficulty: 'Easy', controls: { ps: 'RS: Hold left or right (perpendicular to movement)', xbox: 'RS: Hold left or right (perpendicular to movement)' }, bestFor: 'Close control, beating a pressing defender', when: 'When a defender is sprinting towards you head-on', tip: 'Simple but incredibly effective. Use it to sidestep lunging tackles.' },
  { name: 'Drag Back', stars: 2, difficulty: 'Easy', controls: { ps: 'R1 + LS back (relative to player facing)', xbox: 'RB + LS back (relative to player facing)' }, bestFor: 'Creating space, changing direction quickly', when: 'When you need to quickly reverse direction or pull back from a defender', tip: 'Great for resetting your attack. Chain with a sprint boost for quick acceleration.' },
  { name: 'Fake Shot', stars: 2, difficulty: 'Easy', controls: { ps: '⚫ then ✖ (shoot then pass quickly)', xbox: 'B then A (shoot then pass quickly)' }, bestFor: 'Deceiving goalkeepers and defenders', when: 'Inside the box when approaching GK, or to change direction', tip: 'Hold a direction while performing for a fake shot exit. The most versatile skill in the game.' },
  { name: 'Heel to Ball Roll', stars: 3, difficulty: 'Medium', controls: { ps: 'Fake shot then RS left or right', xbox: 'Fake shot then RS left or right' }, bestFor: 'Quick direction change after a fake shot', when: 'When a defender buys the fake shot and you need to go sideways', tip: 'Chain: fake shot stop → heel to ball roll → accelerate away. Very hard to predict.' },
  { name: 'Heel Flick Turn', stars: 3, difficulty: 'Medium', controls: { ps: 'RS: flick back then left or right', xbox: 'RS: flick back then left or right' }, bestFor: 'Quick 90-degree turns with flair', when: 'When receiving the ball with your back to goal', tip: 'New in FC 26. Excellent for CAMs and CFs with back-to-goal play.' },
  { name: 'La Croqueta', stars: 4, difficulty: 'Medium', controls: { ps: 'L1 + RS left or right', xbox: 'LB + RS left or right' }, bestFor: 'Tight-space dribbling, evading tackles', when: 'In congested midfield areas or when a defender is jockeying you', tip: 'The ball stays very close to the player. Great for keeping possession under pressure.' },
  { name: 'McGeady Spin', stars: 4, difficulty: 'Medium', controls: { ps: 'RS: flick forward then left or right (45° angle)', xbox: 'RS: flick forward then left or right (45° angle)' }, bestFor: 'Beating a defender on the wing', when: 'While running down the touchline with a defender beside you', tip: 'One of the best wing skills. Exit direction is at a sharp angle — perfect for cutting inside.' },
  { name: 'Berba Spin', stars: 4, difficulty: 'Medium', controls: { ps: 'RS: flick left or right, then flick up (relative to movement)', xbox: 'RS: flick left or right, then flick up (relative to movement)' }, bestFor: 'Sharp 90-degree turn past a defender', when: 'While running forward and you want to quickly cut sideways', tip: 'Named after Berbatov. Very effective when approaching a defender at speed.' },
  { name: 'Roulette', stars: 4, difficulty: 'Medium', controls: { ps: 'RS: quarter circle from back to side', xbox: 'RS: quarter circle from back to side' }, bestFor: 'Smooth 180/360 turn past close defenders', when: 'When a defender is tight on you and you need to spin away', tip: 'Classic Zidane move. Keep the left stick neutral during execution for best results.' },
  { name: 'Scoop Turn', stars: 4, difficulty: 'Medium', controls: { ps: 'Fake shot + direction (while standing or slow jog)', xbox: 'Fake shot + direction (while standing or slow jog)' }, bestFor: 'Quick turns in tight spaces, volley setups', when: 'When stationary or slowly moving and you want a quick flick turn', tip: 'Can be chained into a volley for spectacular goals. Must NOT be sprinting.' },
  { name: 'Drag to Chop', stars: 4, difficulty: 'Medium', controls: { ps: 'RS: hold back, then flick left or right', xbox: 'RS: hold back, then flick left or right' }, bestFor: 'Dragging the ball back then chopping sideways', when: 'When facing a defender and you want to create an angle', tip: 'New in FC 26. Combines drag back with a sharp chop — great for creating shooting angles.' },
  { name: 'Elastico', stars: 5, difficulty: 'Hard', controls: { ps: 'RS: ↗ then ↙ (half-circle clockwise)', xbox: 'RS: ↗ then ↙ (half-circle clockwise)' }, bestFor: '1v1 situations, creating space on the wing', when: 'While sprinting diagonally towards the defender', tip: 'Works best when running at 45° angle. The double touch fools defenders completely.' },
  { name: 'Reverse Elastico', stars: 5, difficulty: 'Hard', controls: { ps: 'RS: ↙ then ↗ (half-circle counter-clockwise)', xbox: 'RS: ↙ then ↗ (half-circle counter-clockwise)' }, bestFor: 'Mirror of Elastico, goes opposite direction', when: 'When running at an angle and defender expects the Elastico', tip: 'Mix with regular Elastico to be unpredictable. Same setup, opposite exit.' },
  { name: 'Rainbow Flick', stars: 5, difficulty: 'Hard', controls: { ps: 'RS: flick back, then flick forward twice quickly', xbox: 'RS: flick back, then flick forward twice quickly' }, bestFor: 'Lobbing the ball over a defender', when: 'When a defender is directly in front and you want to flick over them', tip: 'High risk, high reward. Best used sparingly or to set up a volley. Very flashy.' },
];
